version: '2'
services:
  python:
    image: gcr.io/google-appengine/python
    volumes:
      - ./python/:/code
    entrypoint: watchmedo auto-restart --recursive --pattern="*.py" --directory="." python mypackage/run.py


  python-tests:
    image: gcr.io/google-appengine/python
    volumes:
      - ./python/:/code
    entrypoint: watchmedo auto-restart --recursive --pattern="*.py" --directory="." pytest
    depends_on:
      - python

